package ca.docnest.shared.protocol;

/**
 * @brief Packet semantics used throughout the DocNest protocol.
 *
 * @details
 * <ul>
 *   <li><b>filename</b> - User-visible file name supplied by the client.</li>
 *   <li><b>fileId</b> - Internal unique identifier generated by the server.</li>
 * </ul>
 *
 * Clients interact using filenames, while the server resolves filenames to
 * internal file identifiers using metadata records.
 *
 * All physical storage operations should use {@code fileId}.
 */

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * @class PacketBuilder
 * @brief Factory and utility class for constructing protocol packets.
 *
 * @details
 * The {@code PacketBuilder} class centralizes creation of all packet types used
 * by the DocNest client-server protocol.
 *
 * It provides helper methods for:
 * <ul>
 *   <li>Building JSON-based request and response packets</li>
 *   <li>Building binary chunk packets for file transfer</li>
 *   <li>Serializing Java objects into JSON bytes</li>
 *   <li>Parsing raw bytes into JSON trees</li>
 *   <li>Splitting files into fixed-size chunks</li>
 *   <li>Validating received chunks</li>
 * </ul>
 *
 * This class uses only static methods and should not be instantiated.
 */
public class PacketBuilder {

    /**
     * @brief Shared JSON mapper used for serialization and parsing.
     */
    private static final ObjectMapper mapper = new ObjectMapper();

    /**
     * @brief Maximum payload size for a transfer chunk.
     *
     * @details
     * File data is split into blocks of 4096 bytes during upload/download.
     */
    public static final int CHUNK_SIZE = 4096;

    /**
     * @brief Builds a protocol error packet.
     *
     * @param code Numeric error code.
     * @param message Human-readable error message.
     * @param details Additional diagnostic details.
     *
     * @return A {@link DataPacket} with command type {@code ERROR}.
     */
    public static DataPacket buildErrorPacket(int code, String message, String details)
    {
        ErrorPayload payload = new ErrorPayload(code, message, details);
        return buildJsonPacket(PacketType.ERROR, payload);
    }

    // ---------------------------------------------------------
    // JSON → byte[]
    // ---------------------------------------------------------

    /**
     * @brief Serializes an object into JSON bytes.
     *
     * @param obj The object to serialize.
     *
     * @return UTF-8 encoded JSON bytes.
     *
     * @throws RuntimeException If serialization fails.
     */
    public static byte[] jsonToBytes(Object obj) {
        try {
            return mapper.writeValueAsBytes(obj);
        } catch (Exception e) {
            throw new RuntimeException("Failed to serialize JSON", e);
        }
    }

    // ---------------------------------------------------------
    // byte[] → JSON tree
    // ---------------------------------------------------------

    /**
     * @brief Parses raw bytes into a JSON tree.
     *
     * @param data Byte array containing JSON data.
     *
     * @return Parsed {@link JsonNode} tree.
     *
     * @throws RuntimeException If parsing fails.
     */
    public static JsonNode bytesToJson(byte[] data) {
        try {
            return mapper.readTree(data);
        } catch (Exception e) {
            throw new RuntimeException("Failed to parse JSON", e);
        }
    }

    // ---------------------------------------------------------
    // Build a JSON-based DataPacket
    // ---------------------------------------------------------

    /**
     * @brief Builds a packet whose payload is JSON.
     *
     * @param type Packet command type.
     * @param jsonObject Java object to serialize into JSON.
     *
     * @return A new {@link DataPacket}.
     */
    public static DataPacket buildJsonPacket(PacketType type, Object jsonObject) {
        byte[] payload = jsonToBytes(jsonObject);
        return new DataPacket(type, payload);
    }

    // ---------------------------------------------------------
    // Split a byte[] into 4096-byte chunks
    // ---------------------------------------------------------

    /**
     * @brief Splits file data into fixed-size chunks.
     *
     * @details
     * Divides the supplied byte array into blocks no larger than
     * {@link #CHUNK_SIZE}. Used for upload and download transfers.
     *
     * @param fileData Complete file contents.
     *
     * @return List of chunk byte arrays.
     */
    public static List<byte[]> splitIntoChunks(byte[] fileData) {
        List<byte[]> chunks = new ArrayList<>();

        int offset = 0;
        while (offset < fileData.length) {
            int remaining = fileData.length - offset;
            int size = Math.min(CHUNK_SIZE, remaining);

            byte[] chunk = new byte[size];
            System.arraycopy(fileData, offset, chunk, 0, size);

            chunks.add(chunk);
            offset += size;
        }

        return chunks;
    }

    // ---------------------------------------------------------
    // Build a binary chunk packet
    // ---------------------------------------------------------

    /**
     * @brief Builds a binary chunk packet for file transfer.
     *
     * @details
     * Validates the chunk before creating a packet. The chunk must be:
     * <ul>
     *   <li>Non-null</li>
     *   <li>Non-empty</li>
     *   <li>No larger than {@link #CHUNK_SIZE}</li>
     * </ul>
     *
     * @param type Packet type such as {@code UPLOAD_CHUNK} or {@code DOWNLOAD_CHUNK}.
     * @param chunk Binary data chunk.
     *
     * @return A new chunk packet.
     *
     * @throws IllegalArgumentException If the chunk is invalid.
     */
    public static DataPacket buildChunkPacket(PacketType type, byte[] chunk) {
        if (chunk == null) {
            throw new IllegalArgumentException("Chunk is null");
        }

        if (chunk.length == 0) {
            throw new IllegalArgumentException("Chunk is empty");
        }

        if (chunk.length > CHUNK_SIZE) {
            throw new IllegalArgumentException("Chunk exceeds 4096 bytes");
        }
        return new DataPacket(type, chunk);
    }

    // ---------------------------------------------------------
    // Validate a received chunk
    // ---------------------------------------------------------

    /**
     * @brief Validates a received chunk payload.
     *
     * @param chunk Chunk data to validate.
     *
     * @return {@code true} if valid; otherwise {@code false}.
     */
    public static boolean isValidChunk(byte[] chunk) {
        return chunk != null && chunk.length > 0 && chunk.length <= CHUNK_SIZE;
    }

    // ---------------------------------------------------------
    // LOGIN / LOGIN_RESPONSE
    // ---------------------------------------------------------

    /**
     * @brief Builds a login request packet.
     *
     * @param username Username credential.
     * @param password Password credential.
     *
     * @return LOGIN packet.
     */
    public static DataPacket buildLoginPacket(String username, String password) {
        var json = Map.of(
                "username", username,
                "password", password
        );
        return buildJsonPacket(PacketType.LOGIN, json);
    }

    /**
     * @brief Builds a login response packet.
     *
     * @param success Whether authentication succeeded.
     * @param message Response message.
     *
     * @return LOGIN_RESPONSE packet.
     */
    public static DataPacket buildLoginResponsePacket(boolean success, String message) {
        var json = Map.of(
                "success", success,
                "message", message
        );
        return buildJsonPacket(PacketType.LOGIN_RESPONSE, json);
    }

    // ---------------------------------------------------------
    // LIST_FILES / LIST_FILES_RESPONSE
    // ---------------------------------------------------------

    /**
     * @brief Builds a list files request packet.
     *
     * @return LIST_FILES packet.
     */
    public static DataPacket buildListFilesPacket() {
        return buildJsonPacket(PacketType.LIST_FILES, Map.of());
    }

    /**
     * @brief Builds a list files response packet.
     *
     * @param records Collection of metadata records.
     *
     * @return LIST_FILES_RESPONSE packet.
     */
    public static DataPacket buildListFilesResponsePacket(java.util.List<?> records) {
        return buildJsonPacket(
                PacketType.LIST_FILES_RESPONSE,
                java.util.Map.of("files", records)
        );
    }

    // ---------------------------------------------------------
    // UPLOAD_INIT / UPLOAD_READY
    // ---------------------------------------------------------

    /**
     * @brief Builds an upload initialization request.
     *
     * @param filename Original filename.
     * @param size File size in bytes.
     * @param info Additional descriptive info.
     *
     * @return UPLOAD_INIT packet.
     */
    public static DataPacket buildUploadInitPacket(String filename, long size, String info) {
        var json = Map.of(
                "filename", filename,
                "size", size,
                "info", info == null ? "" : info
        );
        return buildJsonPacket(PacketType.UPLOAD_INIT, json);
    }

    /**
     * @brief Builds an upload-ready acknowledgment packet.
     *
     * @return UPLOAD_READY packet.
     */
    public static DataPacket buildUploadReadyPacket() {
        return buildJsonPacket(PacketType.UPLOAD_READY, Map.of());
    }

    // ---------------------------------------------------------
    // UPLOAD_CHUNK / COMPLETE / RESULT
    // ---------------------------------------------------------

    /**
     * @brief Builds an upload chunk packet.
     *
     * @param chunk Binary chunk data.
     *
     * @return UPLOAD_CHUNK packet.
     */
    public static DataPacket buildUploadChunkPacket(byte[] chunk) {
        return buildChunkPacket(PacketType.UPLOAD_CHUNK, chunk);
    }

    /**
     * @brief Builds an upload-complete packet.
     *
     * @return UPLOAD_COMPLETE packet.
     */
    public static DataPacket buildUploadCompletePacket() {
        return buildJsonPacket(PacketType.UPLOAD_COMPLETE, Map.of());
    }

    /**
     * @brief Builds an upload result packet.
     *
     * @param success Whether upload succeeded.
     * @param message Result message.
     *
     * @return UPLOAD_RESULT packet.
     */
    public static DataPacket buildUploadResultPacket(boolean success, String message) {
        var json = Map.of(
                "success", success,
                "message", message
        );
        return buildJsonPacket(PacketType.UPLOAD_RESULT, json);
    }

    // ---------------------------------------------------------
    // DOWNLOAD
    // ---------------------------------------------------------

    /**
     * @brief Builds a download initialization request.
     *
     * @param filename Requested filename.
     *
     * @return DOWNLOAD_INIT packet.
     */
    public static DataPacket buildDownloadInitPacket(String filename) {
        var json = Map.of(
                "filename", filename
        );
        return buildJsonPacket(PacketType.DOWNLOAD_INIT, json);
    }

    /**
     * @brief Builds a download-ready response packet.
     *
     * @param filename Requested filename.
     * @param size File size in bytes.
     *
     * @return DOWNLOAD_READY packet.
     */
    public static DataPacket buildDownloadReadyPacket(String filename, long size) {
        var json = Map.of(
                "filename", filename,
                "size", size
        );
        return buildJsonPacket(PacketType.DOWNLOAD_READY, json);
    }

    /**
     * @brief Builds a download chunk packet.
     *
     * @param chunk Binary data chunk.
     *
     * @return DOWNLOAD_CHUNK packet.
     */
    public static DataPacket buildDownloadChunkPacket(byte[] chunk) {
        return buildChunkPacket(PacketType.DOWNLOAD_CHUNK, chunk);
    }

    /**
     * @brief Builds a download complete packet including filename.
     *
     * @param filename Filename associated with completed transfer.
     *
     * @return DOWNLOAD_COMPLETE packet.
     */
    public static DataPacket buildDownloadCompletePacket(String filename) {
        var json = Map.of(
                "filename", filename
        );
        return buildJsonPacket(PacketType.DOWNLOAD_COMPLETE, json);
    }

    /**
     * @brief Builds an empty download complete packet.
     *
     * @return DOWNLOAD_COMPLETE packet.
     */
    public static DataPacket buildDownloadCompletePacket() {
        return buildJsonPacket(PacketType.DOWNLOAD_COMPLETE, Map.of());
    }

    // ---------------------------------------------------------
    // DELETE_FILE / DELETE_RESPONSE
    // ---------------------------------------------------------

    /**
     * @brief Builds a delete file request packet.
     *
     * @param filename File to delete.
     *
     * @return DELETE_FILE packet.
     */
    public static DataPacket buildDeleteFilePacket(String filename) {
        var json = Map.of(
                "filename", filename
        );
        return buildJsonPacket(PacketType.DELETE_FILE, json);
    }

    /**
     * @brief Builds a delete response packet.
     *
     * @param success Whether deletion succeeded.
     * @param message Result message.
     *
     * @return DELETE_RESPONSE packet.
     */
    public static DataPacket buildDeleteResponsePacket(boolean success, String message) {
        var json = Map.of(
                "success", success,
                "message", message
        );
        return buildJsonPacket(PacketType.DELETE_RESPONSE, json);
    }

    // ---------------------------------------------------------
    // LOGOUT
    // ---------------------------------------------------------

    /**
     * @brief Builds a logout request packet.
     *
     * @return LOGOUT packet.
     */
    public static DataPacket buildLogoutPacket() {
        return buildJsonPacket(PacketType.LOGOUT, Map.of());
    }

}